# Generated by Django 4.0.1 on 2023-04-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('full_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
